apiVersion: apps/v1
kind: Deployment
metadata:
  name: labeled-workload
  labels:
    foo: bar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: labeled-workload
  template:
    metadata:
      labels:
        app: labeled-workload
    spec:
      containers:
        - name: echo
          image: busybox:latest
          command:
            - "sleep"
            - "1000"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: httpport
